export const LOADUSER_SUCCESS = "LOADUSER_SUCCESS";
export const CREATEUSER_SUCCESS = "CREATEUSER_SUCCESS";
export const UPDATEEUSER_SUCCESS = "UPDATEEUSER_SUCCESS";
export const DELETEUSER_SUCCESS = "DELETEUSER_SUCCESS";

export const LOAD_USER_GROUP_SUCCESS = "LOAD_USER_GROUP_SUCCESS";
export const CREATE_USER_GROUP_SUCCESS = "CREATE_USER_GROUP_SUCCESS";
export const UPDATE_USER_GROUP_SUCCESS = "UPDATE_USER_GROUP_SUCCESS";
export const DELETE_USER_GROUP_SUCCESS = "DELETE_USER_GROUP_SUCCESS";

export const LOAD_EMERGENCY_CONTACT_SUCCESS = "LOAD_EMERGENCY_CONTACT_SUCCESS";
export const DELETE_EMERGENCY_CONTACT_SUCCESS =
  "DELETE_EMERGENCY_CONTACT_SUCCESS";
export const CREATE_EMERGENCY_CONTACT_SUCCESS =
  "CREATE_EMERGENCY_CONTACT_SUCCESS";
export const UPDATE_EMERGENCY_CONTACT_SUCCESS =
  "UPDATE_EMERGENCY_CONTACT_SUCCESS";

export const LOAD_ASSIGN_EMERGENCY_CONTACT_SUCCESS =
  "LOAD_ASSIGN_EMERGENCY_CONTACT_SUCCESS";
export const CREATE_ASSIGN_EMERGENCY_CONTACT_SUCCESS =
  "CREATE_ASSIGN_EMERGENCY_CONTACT_SUCCESS";
export const UPDATE_ASSIGN_EMERGENCY_CONTACT_SUCCESS =
  "UPDATE_ASSIGN_EMERGENCY_CONTACT_SUCCESS";
export const DELETE_ASSIGN_EMERGENCY_CONTACT_SUCCESS =
  "DELETE_ASSIGN_EMERGENCY_CONTACT_SUCCESS";

export const LOAD_ASSIGNED_DESIGNATION_SUCCESS =
  "LOAD_ASSIGNED_DESIGNATION_SUCCESS";
export const CREATE_USER_DESIGNATION_SUCCESS =
  "CREATE_USER_DESIGNATION_SUCCESS";
export const UPDATE_USER_DESIGNATION_SUCCESS =
  "UPDATE_USER_DESIGNATION_SUCCESS";
export const DELETE_USER_DESIGNATION_SUCCESS =
  "DELETE_USER_DESIGNATION_SUCCESS";

export const LOAD_COVID_STATE_SUCCESS = "LOAD_COVID_STATE_SUCCESS";
export const CREATE_COVID_STATE_SUCCESS = "CREATE_COVID_STATE_SUCCESS";
export const UPDATE_COVID_STATE_SUCCESS = "UPDATE_COVID_STATE_SUCCESS";
export const DELETE_COVID_STATE_SUCCESS = "DELETE_COVID_STATE_SUCCESS";

export const LOAD_GLOBAL_SETTING_SUCCESS = "LOAD_GLOBAL_SETTING_SUCCESS";
export const CREATE_GLOBAL_SETTING_SUCCESS = "CREATE_GLOBAL_SETTING_SUCCESS";
export const UPDATE_TEMPERATURE_RANGE = "UPDATE_TEMPERATURE_RANGE";
export const LOAD_GLOBAL_SETTING_WITHOUT_API_SUCCESS =
  "LOAD_GLOBAL_SETTING_WITHOUT_API_SUCCESS";
export const LOAD_TEMPERATURE_RANGE_WITHOUT_API_SUCCESS =
  "LOAD_TEMPERATURE_RANGE_WITHOUT_API_SUCCESS";

export const LOAD_FAQ_SUCCESS = "LOAD_FAQ_SUCCESS";
export const DELETE_FAQ_SUCCESS = "DELETE_FAQ_SUCCESS";

export const LOAD_LIST_SITE_SUCCESS = "LOAD_LIST_SITE_SUCCESS";
export const CREATE_SITE_SUCCESS = "CREATE_SITE_SUCCESS";
export const UPDATE_SITE_SUCCESS = "UPDATE_SITE_SUCCESS";
export const DELETE_SITE_SUCCESS = "DELETE_SITE_SUCCESS";
export const DELETE_SITE_FLOOR_SUCCESS = "DELETE_SITE_FLOOR_SUCCESS";
export const UPDATE_SITE_FLOOR_SUCCESS = "UPDATE_SITE_FLOOR_SUCCESS";

export const LOAD_FLOOR_SUCCESS = "LOAD_FLOOR_SUCCESS";
export const CREATE_FLOOR_SUCCESS = "CREATE_FLOOR_SUCCESS";
export const UPDATE_FLOOR_SUCCESS = "UPDATE_FLOOR_SUCCESS";
export const DELETE_FLOOR_SUCCESS = "DELETE_FLOOR_SUCCESS";

export const LOAD_LOCATION_SUCCESS = "LOAD_LOCATION_SUCCESS";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";

export const LOAD_ASSIGN_FAQ_SUCCESS = "LOAD_ASSIGN_FAQ_SUCCESS";
export const CREATE_ASSIGN_FAQ_SUCCESS = "CREATE_ASSIGN_FAQ_SUCCESS";
export const DELETE_ASSIGN_FAQ_SUCCESS = "DELETE_ASSIGN_FAQ_SUCCESS";
export const CHANGE_ASSIGN_FAQ_STATUS_SUCCESS =
  "CHANGE_ASSIGN_FAQ_STATUS_SUCCESS";

export const LOAD_ALL_TEAMS = "LOAD_ALL_TEAMS";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const UPDATE_TEAM_SUCCESS = "UPDATE_TEAM_SUCCESS";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";

export const LOAD_ALL_QUESTIONAIRE = "LOAD_ALL_QUESTIONAIRE";
export const CREATE_QUESTIONAIRE_SUCCESS = "CREATE_QUESTIONAIRE_SUCCESS";
export const DELETE_QUESTIONAIRE_SUCCESS = "DELETE_QUESTIONAIRE_SUCCESS";
export const UPDATE_QUESTIONAIRE_SUCCESS = "UPDATE_QUESTIONAIRE_SUCCESS";

export const ASSIGN_USERGROUP_QUESTIONAIRE = "ASSIGN_USERGROUP_QUESTIONAIRE";
export const ASSIGN_QUESTIONAIRE_USERGROUP = "ASSIGN_QUESTIONAIRE_USERGROUP";
export const CHANGE_QUESTIONAIRE_STATUS = "CHANGE_QUESTIONAIRE_STATUS";
export const DELETE_QUESTIONAIRE_USERGROUP = "DELETE_QUESTIONAIRE_USERGROUP";

export const LIST_ALL_QUESTIONS = "LIST_ALL_QUESTIONS";
export const DELETE_SELECTED_BOOLEAN_QUESTION =
  "DELETE_SELECTED_BOOLEAN_QUESTION";
export const DELETE_SELECTED_DATE_QUESTION = "DELETE_SELECTED_DATE_QUESTION";
export const DELETE_FREETEXT_QUESTION = "DELETE_FREETEXT_QUESTION";
export const DELETE_MULTICHOICE_QUESTION = "DELETE_MULTICHOICE_QUESTION";
export const DELETE_NUMERIC_QUESTION = "DELETE_NUMERIC_QUESTION";
export const DELETE_SINGLECHOICE_QUESTION = "DELETE_SINGLECHOICE_QUESTION";

export const LOAD__SITE_SECURITY_SUCCESS = "LOAD__SITE_SECURITY_SUCCESS";

export const LIST_ALL_WORKFLOW = "LIST_ALL_WORKFLOW";
export const CREATE_WORKFLOW_SUCCESS = "CREATE_WORKFLOW_SUCCESS";
export const UPDATE_WORKFLOW_SUCCESS = "UPDATE_WORKFLOW_SUCCESS";
export const DELETE_WORKFLOW_SUCCESS = "DELETE_WORKFLOW_SUCCESS";
